# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['192.168.1.254:9090']

  - job_name: 'ceph-exporter'
    static_configs:
      - targets: ['192.168.1.254:9128']

  - job_name: 'libvirt'
    static_configs:
      - targets: ['192.168.1.254:9177']

  - job_name: 'wmi_exporter'
    static_configs:
      - targets: ['192.168.122.140:9182']

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
          - '192.168.1.254:9100'
          - '192.168.1.31:9100'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: 'instance'
        regex: '([\d\.]+):\d+'
        replacement: '${1}'

  - job_name: 'ceph-mgr'
    static_configs:
      - targets:
        - '192.168.1.1:9283'
        - '192.168.1.2:9283'
        - '192.168.1.3:9283'
        - '192.168.1.11:9283'
        - '192.168.1.12:9283'
        - '192.168.1.13:9283'

  - job_name: 'dcgm-exporter'
    static_configs:
      - targets:
        - '192.168.1.31:9400'

  - job_name: 'snmp-exporter-idrac'
    static_configs:
      - targets:
        - '192.168.0.120'
    metrics_path: '/snmp'
    params:
      module: [idrac_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.31:9116

  - job_name: 'mysqld-exporter'
    static_configs:
      - targets:
        - '192.168.1.31:9104'
